### ISSUE TITLE
How does it run?

### ISSUE THREAD

**Issue by Joseiltonslv** [RuiJMoreira/KodiPortugalRedirectService#1]
I'm trying to figure out how to run it but there's no step by step, and where I'm trying to run it on my cell phone, because python has a way, but I don't even know where it starts

**Comment by RuiJMoreira** [comment]
Hi!
The project is dependent on python and php.
For the TVI channels you only need php, because a different token is needed for each client that makes a request to watch that channel. For this you are going to need a php server, in order to use the php scripts, you can use a free online hosting service and upload the files, then you just need to type "your server address /file.php" in the address bar, or simply put the link in your m3u playlist (some software can't interpret the redirect, this was only tested and intended for kodi). 
The euro news, because a single token servers many clients, I create a python script that generates a php page that just redirects the user upon request. The ideia is having the python script in your server run each 12 hours, for example, creating a php file with just the link.
